### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Dacaly** [Absolute-Development/discord-music-core#1]
Uhm, hello. A short question. What does this mean?

```internal/modules/cjs/loader.js:797
2020-01-10T20:58:28.960124+00:00 app[worker.1]:     throw err;
2020-01-10T20:58:28.960126+00:00 app[worker.1]:     ^
2020-01-10T20:58:28.960128+00:00 app[worker.1]: 
2020-01-10T20:58:28.960131+00:00 app[worker.1]: Error: Cannot find module 'm3u8stream/lib/parse-time'
2020-01-10T20:58:28.960138+00:00 app[worker.1]: Require stack:
2020-01-10T20:58:28.960141+00:00 app[worker.1]: - /app/node_modules/discord-music-core/node_modules/ytdl-core/lib/info-extras.js
2020-01-10T20:58:28.960145+00:00 app[worker.1]: - /app/node_modules/discord-music-core/node_modules/ytdl-core/lib/info.js
2020-01-10T20:58:28.960147+00:00 app[worker.1]: - /app/node_modules/discord-music-core/node_modules/ytdl-core/lib/index.js
2020-01-10T20:58:28.960150+00:00 app[worker.1]: - /app/node_modules/discord-music-core/core.js
2020-01-10T20:58:28.960152+00:00 app[worker.1]: - /app/node_modules/discord-music-core/index.js
2020-01-10T20:58:28.960154+00:00 app[worker.1]: - /app/commands/music/loop.js
2020-01-10T20:58:28.960156+00:00 app[worker.1]: - /app/index.js
2020-01-10T20:58:28.960158+00:00 app[worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
2020-01-10T20:58:28.960160+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
2020-01-10T20:58:28.960163+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:849:19)
2020-01-10T20:58:28.960165+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2020-01-10T20:58:28.960168+00:00 app[worker.1]:     at Object.<anonymous> (/app/node_modules/discord-music-core/node_modules/ytdl-core/lib/info-extras.js:5:21)
2020-01-10T20:58:28.960170+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:956:30)
2020-01-10T20:58:28.960172+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
2020-01-10T20:58:28.960174+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:812:32)
2020-01-10T20:58:28.960176+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-01-10T20:58:28.960179+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:849:19)
2020-01-10T20:58:28.960181+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2020-01-10T20:58:28.960183+00:00 app[worker.1]:     at Object.<anonymous> (/app/node_modules/discord-music-core/node_modules/ytdl-core/lib/info.js:6:21)
2020-01-10T20:58:28.960185+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:956:30)
2020-01-10T20:58:28.960187+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
2020-01-10T20:58:28.960190+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:812:32)
2020-01-10T20:58:28.960192+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
2020-01-10T20:58:28.960194+00:00 app[worker.1]:   code: 'MODULE_NOT_FOUND',
2020-01-10T20:58:28.960196+00:00 app[worker.1]:   requireStack: [
2020-01-10T20:58:28.960199+00:00 app[worker.1]:     '/app/node_modules/discord-music-core/node_modules/ytdl-core/lib/info-extras.js',
2020-01-10T20:58:28.960201+00:00 app[worker.1]:     '/app/node_modules/discord-music-core/node_modules/ytdl-core/lib/info.js',
2020-01-10T20:58:28.960203+00:00 app[worker.1]:     '/app/node_modules/discord-music-core/node_modules/ytdl-core/lib/index.js',
2020-01-10T20:58:28.960205+00:00 app[worker.1]:     '/app/node_modules/discord-music-core/core.js',
2020-01-10T20:58:28.960207+00:00 app[worker.1]:     '/app/node_modules/discord-music-core/index.js',
2020-01-10T20:58:28.960209+00:00 app[worker.1]:     '/app/commands/music/loop.js',
2020-01-10T20:58:28.960211+00:00 app[worker.1]:     '/app/index.js'
2020-01-10T20:58:28.960213+00:00 app[worker.1]:   ]
2020-01-10T20:58:28.960215+00:00 app[worker.1]: }

**Comment by sarhandev** [comment]
This will fix your problem write it in Console

> cp -r ./node_modules/m3u8stream/dist ./node_modules/m3u8stream/lib

**Comment by nai-lyssa** [comment]
Hello! I need a bit of help with the tsconfig.json file. I copied and pasted it into there and at the first bracket there is a red line under it, it is the only one I am having trouble with. Thank you!

![Screenshot 2020-10-10 001432](https://user-images.githubusercontent.com/72640467/95645497-9d42cf80-0a8d-11eb-89b8-b1477603c874.png)
